"""Static configuration for private background-image uploads."""

import os
from pathlib import Path


BACKGROUND_UPLOAD_FIELD = "file"
BACKGROUND_MAX_FILE_BYTES = 10 * 1024 * 1024
BACKGROUND_MAX_REQUEST_BYTES = 11 * 1024 * 1024
BACKGROUND_MAX_PIXELS = 20_000_000
BACKGROUND_MAX_WIDTH = 2560
BACKGROUND_MAX_HEIGHT = 1440
BACKGROUND_WEBP_QUALITY = 84
BACKGROUND_ALLOWED_IMAGE_FORMATS = frozenset({"JPEG", "PNG", "WEBP"})
BACKGROUND_OUTPUT_FORMAT = "WEBP"
BACKGROUND_OUTPUT_MIME_TYPE = "image/webp"

_DEFAULT_BACKGROUND_UPLOAD_ROOT = Path(__file__).resolve().parent / "uploads" / "backgrounds"
BACKGROUND_UPLOAD_ROOT = Path(os.environ["BACKGROUND_UPLOAD_ROOT"]) if os.environ.get(
    "BACKGROUND_UPLOAD_ROOT"
) else _DEFAULT_BACKGROUND_UPLOAD_ROOT
