CREATE TABLE IF NOT EXISTS fetch_results (
    id BIGINT NOT NULL AUTO_INCREMENT,
    result_uid VARCHAR(64) NOT NULL,
    task_id BIGINT NULL,
    requested_url TEXT NOT NULL,
    normalized_url TEXT NOT NULL,
    normalized_fingerprint VARCHAR(64) NOT NULL,
    final_url TEXT NULL,
    normalized_final_url TEXT NULL,
    normalized_final_fingerprint VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    http_status INT NULL,
    content_type VARCHAR(255) NULL,
    charset VARCHAR(64) NULL,
    bytes_read BIGINT NULL,
    redirect_count INT NOT NULL DEFAULT 0,
    redirect_chain JSON NULL,
    title VARCHAR(500) NULL,
    meta_description TEXT NULL,
    canonical_url TEXT NULL,
    og_title VARCHAR(500) NULL,
    og_description TEXT NULL,
    og_image_url TEXT NULL,
    twitter_title VARCHAR(500) NULL,
    twitter_description TEXT NULL,
    twitter_image_url TEXT NULL,
    favicon_url TEXT NULL,
    apple_touch_icon_url TEXT NULL,
    language VARCHAR(64) NULL,
    heading VARCHAR(1000) NULL,
    text_excerpt TEXT NULL,
    content_hash VARCHAR(64) NULL,
    document_metadata_json JSON NULL,
    robots_allowed BOOLEAN NULL,
    robots_status INT NULL,
    etag VARCHAR(500) NULL,
    last_modified VARCHAR(500) NULL,
    fetched_at DATETIME(6) NOT NULL,
    elapsed_ms INT NULL,
    error_code VARCHAR(64) NULL,
    error_message_sanitized VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_fetch_results_result_uid UNIQUE (result_uid),
    CONSTRAINT uq_fetch_results_task_id UNIQUE (task_id),
    CONSTRAINT uq_fetch_results_final_content
        UNIQUE (normalized_final_fingerprint, content_hash),
    CONSTRAINT fk_fetch_results_task
        FOREIGN KEY (task_id) REFERENCES crawl_tasks (id),
    INDEX ix_fetch_results_status_fetched (status, fetched_at),
    INDEX ix_fetch_results_final_fetched
        (normalized_final_fingerprint, fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS discovered_links (
    id BIGINT NOT NULL AUTO_INCREMENT,
    link_uid VARCHAR(64) NOT NULL,
    source_result_id BIGINT NOT NULL,
    source_url TEXT NOT NULL,
    discovered_url TEXT NOT NULL,
    normalized_url TEXT NOT NULL,
    normalized_fingerprint VARCHAR(64) NOT NULL,
    relation_type VARCHAR(64) NOT NULL,
    discovery_type VARCHAR(64) NOT NULL,
    depth INT NOT NULL,
    is_safe BOOLEAN NOT NULL,
    is_same_origin BOOLEAN NOT NULL,
    enqueue_status VARCHAR(32) NOT NULL,
    metadata_json JSON NULL,
    discovered_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_discovered_links_link_uid UNIQUE (link_uid),
    CONSTRAINT uq_discovered_links_source_url
        UNIQUE (source_result_id, normalized_fingerprint),
    CONSTRAINT fk_discovered_links_result
        FOREIGN KEY (source_result_id) REFERENCES fetch_results (id),
    INDEX ix_discovered_links_normalized (normalized_fingerprint),
    INDEX ix_discovered_links_enqueue (enqueue_status, discovered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
