-- Phase 4: forward-only review and publish pipeline; crawler DB only.
CREATE TABLE IF NOT EXISTS review_cases (
    id BIGINT NOT NULL AUTO_INCREMENT,
    review_uid VARCHAR(64) NOT NULL,
    fetch_result_id BIGINT NOT NULL,
    analysis_result_id BIGINT NOT NULL,
    source_content_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    assigned_reviewer_id VARCHAR(128) NULL,
    assigned_at DATETIME(6) NULL,
    submitted_at DATETIME(6) NULL,
    decision_at DATETIME(6) NULL,
    approved_at DATETIME(6) NULL,
    rejected_at DATETIME(6) NULL,
    publish_ready_at DATETIME(6) NULL,
    published_at DATETIME(6) NULL,
    selected_title VARCHAR(500) NULL,
    selected_summary TEXT NULL,
    selected_description TEXT NULL,
    selected_category VARCHAR(64) NULL,
    selected_region VARCHAR(32) NULL,
    selected_language VARCHAR(16) NULL,
    selected_url TEXT NULL,
    selected_logo_asset_id BIGINT NULL,
    risk_acknowledgements JSON NULL,
    override_reasons JSON NULL,
    version INT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_review_cases_uid UNIQUE (review_uid),
    CONSTRAINT fk_review_cases_fetch FOREIGN KEY (fetch_result_id) REFERENCES fetch_results (id),
    CONSTRAINT fk_review_cases_analysis FOREIGN KEY (analysis_result_id) REFERENCES analysis_results (id),
    CONSTRAINT fk_review_cases_logo FOREIGN KEY (selected_logo_asset_id) REFERENCES icon_assets (id),
    INDEX ix_review_cases_analysis (analysis_result_id),
    INDEX ix_review_cases_status_created (status, created_at),
    INDEX ix_review_cases_priority (priority, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS review_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_uid VARCHAR(64) NOT NULL,
    review_case_id BIGINT NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    previous_status VARCHAR(32) NULL,
    next_status VARCHAR(32) NULL,
    reason_code VARCHAR(64) NULL,
    notes_sanitized TEXT NULL,
    metadata_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_review_events_uid UNIQUE (event_uid),
    CONSTRAINT fk_review_events_case FOREIGN KEY (review_case_id) REFERENCES review_cases (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS publish_records (
    id BIGINT NOT NULL AUTO_INCREMENT,
    publish_uid VARCHAR(64) NOT NULL,
    review_case_id BIGINT NOT NULL,
    target_database VARCHAR(64) NOT NULL,
    target_table VARCHAR(64) NOT NULL,
    target_record_id BIGINT NULL,
    target_website_id INT NULL,
    operation_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    source_snapshot JSON NULL,
    target_before_snapshot JSON NULL,
    target_after_snapshot JSON NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64) NULL,
    last_error_sanitized TEXT NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_publish_records_uid UNIQUE (publish_uid),
    CONSTRAINT uq_publish_records_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_publish_records_case FOREIGN KEY (review_case_id) REFERENCES review_cases (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
