-- Phase 3 traceability only. Forward-only and crawler database only.
ALTER TABLE analysis_results
    ADD COLUMN analysis_key VARCHAR(64) NULL,
    ADD COLUMN task_uid VARCHAR(64) NULL,
    ADD COLUMN run_uid VARCHAR(64) NULL,
    ADD COLUMN normalized_url TEXT NULL,
    ADD COLUMN analyzer_type VARCHAR(32) NULL,
    ADD COLUMN provider_name VARCHAR(128) NULL,
    ADD COLUMN model_version VARCHAR(128) NULL,
    ADD COLUMN prompt_version VARCHAR(128) NULL,
    ADD COLUMN taxonomy_version VARCHAR(128) NULL,
    ADD COLUMN scoring_version VARCHAR(128) NULL,
    ADD COLUMN schema_version VARCHAR(128) NULL,
    ADD COLUMN status VARCHAR(32) NULL,
    ADD COLUMN subcategory_suggestion VARCHAR(64) NULL,
    ADD COLUMN quality_reasons_json JSON NULL,
    ADD COLUMN risk_level VARCHAR(16) NULL,
    ADD COLUMN risk_flags_json JSON NULL,
    ADD COLUMN risk_reasons_json JSON NULL,
    ADD COLUMN provider_response_sanitized JSON NULL,
    ADD COLUMN provider_request_hash VARCHAR(64) NULL,
    ADD COLUMN input_snapshot_json JSON NULL,
    ADD COLUMN input_snapshot_hash VARCHAR(64) NULL,
    ADD COLUMN error_code VARCHAR(64) NULL,
    ADD COLUMN error_message_sanitized TEXT NULL,
    ADD COLUMN started_at DATETIME(6) NULL,
    ADD COLUMN completed_at DATETIME(6) NULL,
    ADD COLUMN updated_at DATETIME(6) NULL,
    ADD COLUMN version INT NOT NULL DEFAULT 1,
    ADD CONSTRAINT uq_analysis_results_key UNIQUE (analysis_key),
    ADD INDEX ix_analysis_results_key_status (analysis_key, status);

ALTER TABLE review_cases
    ADD COLUMN source_input_snapshot_hash VARCHAR(64) NULL,
    ADD COLUMN source_analyzer_type VARCHAR(32) NULL,
    ADD COLUMN source_model_version VARCHAR(128) NULL,
    ADD COLUMN source_prompt_version VARCHAR(128) NULL,
    ADD COLUMN source_taxonomy_version VARCHAR(128) NULL,
    ADD COLUMN source_scoring_version VARCHAR(128) NULL;
